apiVersion: v2
appVersion: 2.0.1
description: A Helm chart for Kubernetes
home: https://www.mikroways.net
sources:
  - https://github.com/Mikroways/slo-tracker/charts/slo-tracker
name: slo-tracker
type: application
version: 1.1.1